### ISSUE TITLE
Fails on start

### ISSUE THREAD

**Issue by mcepl** [nogaems/pelican-ert#2]
Just by adding ``pelican-ert`` to ``PLUGINS`` I get the critical error:
```
CRITICAL: AttributeError: module 'pelican-ert' has no attribute 'register'
```

**Comment by nogaems** [comment]
I've just checked it, using upstream version of `pelican` and everything seems to be fine.
In my case I have the following settings in `pelicanconf.py`:
```
 PLUGIN_PATHS = ['./']
 PLUGINS = ['pelican-ert']
```
and remember that you have to clone `pelican-ert` into one of your `PLUGIN_PATHS` directories.

If this doesn't help, please specify your pelican version and config file.

**Comment by mcepl** [comment]
Yes, it was PEBKAC, sorry.
